<?php return array(
    'root' => array(
        'pretty_version' => '1.0.0+no-version-set',
        'version' => '1.0.0.0',
        'type' => 'library',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'reference' => NULL,
        'name' => 'ulaan/tttttttt',
        'dev' => true,
    ),
    'versions' => array(
        'caxy/php-htmldiff' => array(
            'pretty_version' => 'v0.1.14',
            'version' => '0.1.14.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../caxy/php-htmldiff',
            'aliases' => array(),
            'reference' => '3f8ee7edda3d7c6d2e58a02d70a12d3242c84ea5',
            'dev_requirement' => false,
        ),
        'ezyang/htmlpurifier' => array(
            'pretty_version' => 'v4.16.0',
            'version' => '4.16.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ezyang/htmlpurifier',
            'aliases' => array(),
            'reference' => '523407fb06eb9e5f3d59889b3978d5bfe94299c8',
            'dev_requirement' => false,
        ),
        'geshi/geshi' => array(
            'pretty_version' => 'v1.0.9.1',
            'version' => '1.0.9.1',
            'type' => 'library',
            'install_path' => __DIR__ . '/../geshi/geshi',
            'aliases' => array(),
            'reference' => 'fd22ab78481bf90337862b590e6f7517863926b8',
            'dev_requirement' => false,
        ),
        'mistralys/application-utils' => array(
            'pretty_version' => '2.2.9',
            'version' => '2.2.9.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mistralys/application-utils',
            'aliases' => array(),
            'reference' => 'bfa3fc3af72a479fa985b3f2a8cd3fb7d6191970',
            'dev_requirement' => false,
        ),
        'mistralys/text-diff' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mistralys/text-diff',
            'aliases' => array(
                0 => '9999999-dev',
            ),
            'reference' => '40f9b0bc8f0ae3a93bc7495feecee268ac9a1b81',
            'dev_requirement' => false,
        ),
        'neitanod/forceutf8' => array(
            'pretty_version' => 'v2.0.4',
            'version' => '2.0.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../neitanod/forceutf8',
            'aliases' => array(),
            'reference' => 'c1fbe70bfb5ad41b8ec5785056b0e308b40d4831',
            'dev_requirement' => false,
        ),
        'parsecsv/php-parsecsv' => array(
            'pretty_version' => '1.3.2',
            'version' => '1.3.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../parsecsv/php-parsecsv',
            'aliases' => array(),
            'reference' => '2d6236cae09133e0533d34ed45ba1e1ecafffebb',
            'dev_requirement' => false,
        ),
        'ulaan/tttttttt' => array(
            'pretty_version' => '1.0.0+no-version-set',
            'version' => '1.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'reference' => NULL,
            'dev_requirement' => false,
        ),
    ),
);
